"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = 'â”Œâ”€\[ $username$directory$git_branch$nix_shell$container$line_break$character'
line_break = false

[character]
error_symbol = "â””â”€>"
success_symbol = "â””â”€>"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "ï˜ "

[username]
format = "[$user]($style) "
show_always = true

[container]
symbol = "ğŸ“¦"

[nix_shell]
format = '[$symbol (\($name\))]($style) '
symbol = "â„ï¸"

[fill]
symbol = " "
