"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$container$username$directory$git_branch$character"
line_break = false

[character]
error_symbol = "[~>](bold red)"
success_symbol = "[~>](bold green)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "ï˜ "

[username]
format = "[$user]($style) "
show_always = true

[container]
symbol = "ğŸ“¦"
